"""Episode log schema, incremental local writes, resume tracking, and batched
Drive sync.

Design:
- Every finished episode is written IMMEDIATELY as its own small parquet file
  under `local_output_root/episodes/`, named by its (condition, suite, task,
  episode_seed) key. This is the "episode-level incremental save" requirement.
- `remote_output_root` (Drive) is only touched every `sync_every_n_episodes`,
  copying the batch of new local files over in one go -- never one Drive write
  per episode ("Drive에 소량 다발 쓰기 금지").
- Resume checks the PERSISTENT store (remote if configured, else local), since
  local disk does not survive a Colab session restart -- only Drive does.
- `summary.csv` / reports are regenerated by scanning whatever per-episode
  files exist at the time, so a run that dies mid-way still yields a report
  from partial results.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, fields
from pathlib import Path
from typing import Any

import pyarrow as pa
import pyarrow.parquet as pq

# Required fields per the project spec, plus timing-breakdown fields needed for
# the cost-measurement requirement (policy inference / render / physics / reset).
EPISODE_SCHEMA = pa.schema(
    [
        pa.field("task_id", pa.string()),
        pa.field("task_suite", pa.string()),
        pa.field("episode_seed", pa.int64()),
        pa.field("environment_seed", pa.int64()),
        pa.field("policy_seed", pa.int64(), nullable=True),
        pa.field("condition", pa.string()),
        pa.field("candidate_id", pa.int64(), nullable=True),
        # Full per-step action sequence actually executed, shape (T, 7).
        pa.field("action_chunk", pa.list_(pa.list_(pa.float32()))),
        # Full per-step [eef_pos_x, eef_pos_y, eef_pos_z, gripper_qpos_0, gripper_qpos_1],
        # shape (T, 5) -- from the raw env obs's robot_state, not the policy-facing 8D
        # observation.state (which also needs quat->axis-angle; not reconstructed here
        # since this is for visually/numerically checking "did the arm ever get near the
        # object", not for feeding a policy). See replay.py's replay_episode.
        pa.field("state_chunk", pa.list_(pa.list_(pa.float32()))),
        # Step indices (into action_chunk/state_chunk) that got a rendered frame saved to
        # <episode video dir>/step_<i>.png -- see replay.py's video_sample_every_n_steps.
        pa.field("video_frame_steps", pa.list_(pa.int64())),
        pa.field("episode_success", pa.bool_()),
        pa.field("rollout_length", pa.int64()),
        pa.field("checkpoint_name", pa.string()),
        pa.field("checkpoint_hash", pa.string()),
        pa.field("git_commit", pa.string()),
        pa.field("config_file", pa.string()),
        pa.field("execution_time", pa.float64()),
        # Extra fields: cost breakdown + replay-specific provenance.
        pa.field("time_inference_s", pa.float64()),
        pa.field("time_render_s", pa.float64()),
        pa.field("time_physics_s", pa.float64()),
        pa.field("time_reset_s", pa.float64()),
        pa.field("control_mode", pa.string()),
        pa.field("control_freq", pa.int64()),
        # Plumbing verification: the control mode actually read back from the env's
        # controller (robot.controller.use_delta) after reset, NOT just the value we
        # requested -- see harness.read_actual_control_mode. Null if unavailable.
        pa.field("actual_control_mode", pa.string(), nullable=True),
        # Longest consecutive run of "close" (action[:,6] > 0) commands actually
        # executed. Demos show ~15-20 step actuator lag before a close visibly
        # registers (see xgap_code/gripper_metrics.py) -- a run shorter than that
        # cannot physically have grasped, independent of sign convention.
        pa.field("longest_close_run_steps", pa.int64()),
    ]
)


def episode_key(condition: str, task_suite: str, task_id: str, episode_seed: int) -> str:
    # Sanitize for filesystem use -- ':' is invalid in Windows filenames (dev machines
    # run Windows even though Colab/target servers are Linux), and task_id routinely
    # contains ':' (e.g. "libero_10:0" as suite:task_index).
    safe_task = task_id.replace("/", "_").replace(" ", "_").replace(":", "-")
    return f"{condition}__{task_suite}__{safe_task}__{episode_seed}"


@dataclass
class EpisodeRecord:
    task_id: str
    task_suite: str
    episode_seed: int
    environment_seed: int
    condition: str
    action_chunk: list[list[float]]
    state_chunk: list[list[float]]
    video_frame_steps: list[int]
    episode_success: bool
    rollout_length: int
    checkpoint_name: str
    checkpoint_hash: str
    git_commit: str
    config_file: str
    execution_time: float
    time_inference_s: float
    time_render_s: float
    time_physics_s: float
    time_reset_s: float
    control_mode: str
    control_freq: int
    longest_close_run_steps: int
    policy_seed: int | None = None
    candidate_id: int | None = None
    actual_control_mode: str | None = None

    def to_row(self) -> dict[str, Any]:
        return {f.name: getattr(self, f.name) for f in fields(self)}


class EpisodeStore:
    """Local-first, batch-synced-to-Drive episode store with resume support."""

    def __init__(self, local_root: str, remote_root: str | None, sync_every_n_episodes: int):
        self.local_dir = Path(local_root) / "episodes"
        self.remote_dir = Path(remote_root) / "episodes" if remote_root else None
        self.sync_every_n_episodes = max(1, sync_every_n_episodes)
        self.local_dir.mkdir(parents=True, exist_ok=True)
        if self.remote_dir is not None:
            self.remote_dir.mkdir(parents=True, exist_ok=True)
        self._since_last_sync = 0

    # -- resume -----------------------------------------------------------
    def persistent_dir(self) -> Path:
        return self.remote_dir if self.remote_dir is not None else self.local_dir

    def completed_keys(self) -> set[str]:
        d = self.persistent_dir()
        return {p.stem for p in d.glob("*.parquet")}

    def is_done(self, key: str) -> bool:
        return key in self.completed_keys()

    # -- writing ------------------------------------------------------------
    def write_episode(self, key: str, record: EpisodeRecord) -> None:
        row = record.to_row()
        table = pa.Table.from_pylist([row], schema=EPISODE_SCHEMA)
        pq.write_table(table, self.local_dir / f"{key}.parquet")
        self._since_last_sync += 1
        if self._since_last_sync >= self.sync_every_n_episodes:
            self.sync_to_remote()

    def sync_to_remote(self) -> int:
        """Copy any local episode files not yet present remotely, in one batched pass."""
        if self.remote_dir is None:
            self._since_last_sync = 0
            return 0
        remote_existing = {p.name for p in self.remote_dir.glob("*.parquet")}
        n_copied = 0
        for local_file in self.local_dir.glob("*.parquet"):
            if local_file.name not in remote_existing:
                shutil.copy2(local_file, self.remote_dir / local_file.name)
                n_copied += 1
        self._since_last_sync = 0
        return n_copied

    # -- reporting (must tolerate partial results) ---------------------------
    def read_all(self) -> pa.Table:
        d = self.persistent_dir()
        files = sorted(d.glob("*.parquet"))
        if not files:
            return EPISODE_SCHEMA.empty_table()
        tables = [pq.read_table(f, schema=EPISODE_SCHEMA) for f in files]
        return pa.concat_tables(tables)
